[build]
# Force Docker build from server directory only
dockerfile = "server/Dockerfile"
dockerContext = "server"

[deploy]
restartPolicyType = "always"

[experimental]
# Disable auto-detection
configFilePath = "server"