[build]
# Build only the server directory, ignore workspace
workingDir = "server"
buildCommand = "npm install --production"

[deploy] 
# Deploy only the server
startCommand = "node src/server.js"
workingDir = "server"