[build]
# Monorepo: build only from server directory
builder = "nixpacks"
buildCommand = "cd server && npm install --production"

[deploy]
# Deploy from server directory
startCommand = "cd server && node src/server.js"

[build.environment]
# Force Node.js environment
NIXPACKS_NODE_VERSION = "18"